# Generated by Django 3.2.7 on 2021-10-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(max_length=500)),
                ('ag', models.CharField(max_length=500)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.programs')),
            ],
        ),
    ]
